### ISSUE TITLE
Intro: direct seasoned users to relevant parts of UG

### ISSUE THREAD

**Issue by Singa-pirate** [AY2324S1-CS2103T-T08-2/CS2101#1]
possible parts to link to: features, commands, command summary
can mention that they can also got to specific section using table of contents

**Comment by Singa-pirate** [comment]
Should these links be in the intro, or the "about this user guide" section, or both? I feel having them in both is a bit too repetitive.

**Comment by awhb** [comment]
My opinion is having the links in about section makes more sense.

**Comment by Singa-pirate** [comment]
Solved in commit b582c3e.
