### ISSUE TITLE
Features: Combine similar categories

### ISSUE THREAD

**Issue by Singa-pirate** [AY2324S1-CS2103T-T08-2/CS2101#3]
Reason: too many categories cause information overload.

I feel can combine as:
- current 1, 2 -> manage contact information
- current 3, 5 -> view contact information / commands for more efficient networking / to make use of the stored info
- current 4, 8 -> miscellaneous commands
- current 6, 7 -> Other available actions

**Comment by awhb** [comment]
Great idea!

6, 7 can be called accessibility features

**Comment by awhb** [comment]
Anyone has thoughts about this too?

**Comment by Singa-pirate** [comment]
Solved in commit e03c772.
