### ISSUE TITLE
Features: add paddings to diagrams

### ISSUE THREAD

**Issue by Singa-pirate** [AY2324S1-CS2103T-T08-2/CS2101#5]
![image](https://github.com/AY2324S1-CS2103T-T08-2/CS2101/assets/58817781/c9457e16-bd7b-425e-80f2-5bb53f924b53)

More whitespace should be added above and below diagrams

**Comment by awhb** [comment]
Strongly agreed.

**Comment by Eola-Z** [comment]
Do we need to do this for the DG as well?
