### ISSUE TITLE
Features: add detailed annotations on diagrams where applicable 

### ISSUE THREAD

**Issue by Singa-pirate** [AY2324S1-CS2103T-T08-2/CS2101#6]
Where necessary, explain clearly:
- the state before the command
- where should reader be looking at
- the result of the command
- clarification of any UI element that is not straight-forward

![image](https://github.com/AY2324S1-CS2103T-T08-2/CS2101/assets/58817781/70fcac1d-db33-426c-b65e-dfc81553be3e)

e.g. this one should annotate the result of the command, and explain the meaning of 1-star priority

**Comment by awhb** [comment]
Agreed. For style, can refer to examples in other DG parts like below to maintain consistency.

![image](https://github.com/AY2324S1-CS2103T-T08-2/CS2101/assets/104840628/d990a112-d4e9-43d9-8a89-3fb6aab2104c)

**Comment by Singa-pirate** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/CS2101/assets/58817781/b490b061-29db-4f6e-922a-7347a898ef6a)
1. highlight the new phone added

![image](https://github.com/AY2324S1-CS2103T-T08-2/CS2101/assets/58817781/3ac7fc24-2903-4445-a731-19dc2c1c2545)
2. explain priority UI meaning and how has it changed

![image](https://github.com/AY2324S1-CS2103T-T08-2/CS2101/assets/58817781/20044a92-72af-4b96-9ecc-5496ff9e13fa)
3. before/after command

![image](https://github.com/AY2324S1-CS2103T-T08-2/CS2101/assets/58817781/4aadad27-5d13-419f-be22-5a27a9249c80)
4. highlight where is changed, before/after

![image](https://github.com/AY2324S1-CS2103T-T08-2/CS2101/assets/58817781/6bbab1e3-5067-4144-84e5-102e567eb2c7)
5. highlight sort status with reference to items in contact list, adapt the highlight on filter status to be consistent with style

![image](https://github.com/AY2324S1-CS2103T-T08-2/CS2101/assets/58817781/3274fd2e-6a90-4dc4-9770-a5482c6e58b2)
6. highlight filter status with reference to items in contact list

![image](https://github.com/AY2324S1-CS2103T-T08-2/CS2101/assets/58817781/65555acb-6208-41c6-971f-7709796fcaa0)
7. highlight 2nd link of the 2nd contact and connect to the link in browser

![image](https://github.com/AY2324S1-CS2103T-T08-2/CS2101/assets/58817781/759cdebf-df02-4a11-aca2-406493f45de6)
8. same as 7
