### ISSUE TITLE
Features: add command should explain that multiple fields can be added at the same time

### ISSUE THREAD

**Issue by Singa-pirate** [AY2324S1-CS2103T-T08-2/CS2101#7]

**Comment by awhb** [comment]
Agreed. Also linked to a bug that i just saw: 
"To view a comprehensive list of ~~multi-valued~~ fields and their prefixes, go to the start of the [Features section](https://ay2324s1-cs2103t-t08-2.github.io/tp/UserGuide.html#features)."

**Comment by Eola-Z** [comment]
Btw should we wrap the message around a info box?

**Comment by Singa-pirate** [comment]
I feel no need, currently it looks neat, putting too many info boxes in the section may cause some visual confusion.
