### ISSUE TITLE
Features: rephrase and organise filter command section better

### ISSUE THREAD

**Issue by Singa-pirate** [AY2324S1-CS2103T-T08-2/CS2101#8]
![image](https://github.com/AY2324S1-CS2103T-T08-2/CS2101/assets/58817781/2ff5fec8-b9f6-421d-951e-648ff24ac843)

For this part, she mentioned that the phrasing "list of options" is confusing, and there should be a line break after the inner list to separate from the paragraph below

**Comment by Singa-pirate** [comment]
Same for sort command

**Comment by awhb** [comment]
Good catch, thought I had fixed it but I didn't! Thanks!

**Comment by Singa-pirate** [comment]
Solved in commit da4628b.
