### ISSUE TITLE
Add and standardise tip boxes

### ISSUE THREAD

**Issue by Singa-pirate** [AY2324S1-CS2103T-T08-2/CS2101#9]
Add tip box for create contact same name 

Info about format should have ℹ️ and blue colour
Additional note / tip about the command should have 💡 and yellow colour
Warnings about potential mistakes should have ⚠️ and red colour

e.g. index default to 1 should be 💡

**Comment by awhb** [comment]
Yea I wasn't really sure about the standard so just followed a copied colour when creating tipboxes. Whoever's taking this do go through and see if the stuff matches these internal standards we've set!
